version: "3.7"
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    networks:
      - "frontend"
      - "cloud"
      - "ext"
    volumes:
      - ${CONFIGDIR}/cloud/nextcloud/config:/config
      - ${CONFIGDIR}/cloud/nextcloud/data:/data
#    ports:
#      - "443:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - nextcloudDB
    restart: unless-stopped
#   traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=443"
      - "traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}"
      - "traefik.protocol=https"
      - "traefik.frontend.headers.frameDeny=false"

  nextcloudDB:
    image: linuxserver/mariadb:latest
    container_name: nextcloudDB
    networks:
      - "cloud"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_DB}
    volumes:
      - ${CONFIGDIR}/cloud/nextcloudDB:/config
#    ports:
#      - 192.168.1.2:3306:3306
    restart: unless-stopped

  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    networks:
      - "frontend"
      - "cloud"
      - "ext"
#    ports:
#      - 80:80
#      - 3012:3012
    volumes:
      - ${CONFIGDIR}/cloud/bitwarden:/data
    environment:
      - SINGUPS_ALLOWED=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:bitwarden.${DOMAINNAME}"
      - "traefik.frontend.headers.frameDeny=false"

networks:
  frontend:
    external:
      name: "frontend"
  ext:
    external:
      name: "ext"
  cloud:
    name: "cloud"