version: "3.7"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    networks:
      - int
      - cloud
    volumes:
      - ${CONFIGDIR}/cloud/nextcloud/config:/config
      - ${CONFIGDIR}/cloud/nextcloud/data:/data
#    ports:
#      - 443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - nextcloudDB
    restart: unless-stopped
#   traefik
    labels:
      - traefik.enable=true
      - traefik.port=443
      - traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}
      - traefik.protocol=https
      - traefik.frontend.headers.frameDeny=false

  nextcloudDB:
    image: linuxserver/mariadb
    container_name: nextcloudDB
    networks:
      - cloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_DB}
    volumes:
      - ${CONFIGDIR}/cloud/nextcloudDB:/config
#    ports:
#      - 3306:3306
    restart: unless-stopped

  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    networks:
      - int
      - cloud
#    ports:
#      - 80:80
#      - 3012:3012
    volumes:
      - ${CONFIGDIR}/cloud/bitwarden:/data
    environment:
      - SINGUPS_ALLOWED=false
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:bitwarden.${DOMAINNAME}
      - traefik.frontend.headers.frameDeny=false

networks:
  int:
    external:
      name: int
  cloud:
    name: cloud