version: "3.7"
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    networks:
      - "frontend"
      - "cloud"
    volumes:
      - ${CONFIGDIR}/cloud/nextcloud/config:/config
      - ${CONFIGDIR}/cloud/nextcloud/data:/data
#    ports:
#      - "443:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - nextcloudDB
    restart: unless-stopped
#   traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=443"
      - "traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}"
      - "traefik.protocol=https"
      - "traefik.frontend.headers.frameDeny=false"

  nextcloudDB:
    image: linuxserver/mariadb:latest
    container_name: nextcloudDB
    networks:
      - "cloud"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_DB}
    volumes:
      - ${CONFIGDIR}/cloud/nextcloudDB:/config
#    ports:
#      - 192.168.1.2:3306:3306
    restart: unless-stopped

  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    networks:
      - "frontend"
      - "cloud"
#    ports:
#      - "10080:3000"
#      - "10022:22"
    volumes:
      - ${CONFIGDIR}/cloud/gogs:/data
    depends_on:
      - gogsDB
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:gogs.${DOMAINNAME}"
      - "traefik.frontend.headers.frameDeny=false"

  gogsDB:
    image: mysql:latest
    container_name: gogsDB
    networks:
      - "cloud"
    environment:
      - MYSQL_ROOT_PASSWORD=${GOGS_DB_ROOT}
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=${GOGS_DB}
#    ports:
#      - "10036:3306"
    volumes:
      - ${CONFIGDIR}/cloud/gogsDB/config:/etc/mysql/conf.d
      - ${CONFIGDIR}/cloud/gogsDB/db:/var/lib/mysql
    restart: unless-stopped

  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    networks:
      - "frontend"
      - "cloud"
#    ports:
#      - 80:80
#      - 3012:3012
    volumes:
      - ${CONFIGDIR}/cloud/bitwarden:/data
    environment:
      - SINGUPS_ALLOWED=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:bitwarden.${DOMAINNAME}"
      - "traefik.frontend.headers.frameDeny=false"

networks:
  frontend:
    external:
      name: "frontend"
  cloud:
    name: "cloud"