#!/bin/bash
docker-compose -f "${COMPOSE}/monitor/docker-compose.yml" down
docker-compose -f "${COMPOSE}/dev/docker-compose.yml" down
docker-compose -f "${COMPOSE}/download/docker-compose.yml" down
docker-compose -f "${COMPOSE}/cloud/docker-compose.yml" down
docker-compose -f "${COMPOSE}/media/docker-compose.yml" down
docker-compose -f "${COMPOSE}/minecraft/docker-compose.yml" down
docker-compose -f "${COMPOSE}/management/docker-compose.yml" down
docker-compose -f "${COMPOSE}/network/docker-compose.yml" down

