#!/bin/bash
# cd monitor
# docker-compose down
# cd ..

# cd dev
# docker-compose down
# cd ..

# cd download
# docker-compose down
# cd ..

cd cloud
docker-compose down
cd ..

cd media
docker-compose down
cd ..

cd minecraft
docker-compose down
cd ..

# cd school/psyche3dAsteroidViewer
# docker-compose down
# cd ..
# cd ..

cd management
docker-compose down
cd ..

cd network
docker-compose down
cd ..