#!/bin/bash
docker-compose -f "/home/ryan/compose/cloud/docker-compose.yml" down
docker-compose -f "/home/ryan/compose/dev/docker-compose.yml" down
docker-compose -f "/home/ryan/compose/download/docker-compose.yml" down
docker-compose -f "/home/ryan/compose/management/docker-compose.yml" down
docker-compose -f "/home/ryan/compose/media/docker-compose.yml" down
docker-compose -f "/home/ryan/compose/minecraft/docker-compose.yml" down
docker-compose -f "/home/ryan/compose/network/docker-compose.yml" down
docker-compose -f "/home/ryan/compose/test/docker-compose.yml" down

