#!/bin/bash
docker-compose -f "./network/docker-compose.yml" up -d
docker-compose -f "./management/docker-compose.yml" up -d
docker-compose -f "./cloud/docker-compose.yml" up -d
docker-compose -f "./media/docker-compose.yml" up -d
docker-compose -f "./download/docker-compose.yml" up -d
docker-compose -f "./minecraft/docker-compose.yml" up -d
docker-compose -f "./dev/docker-compose.yml" up -d
docker-compose -f "./monitor/docker-compose.yml" up -d
