#!/bin/bash

cd network
docker-compose up -d
cd ..

cd management
docker-compose up -d
cd ..

# cd dev
# docker-compose up -d
# cd ..

cd media
docker-compose up -d
cd ..

# cd download
# docker-compose up -d
# cd ..

cd cloud
docker-compose up -d
cd ..

cd minecraft
docker-compose up -d
cd ..

# cd monitor
# docker-compose up -d
# cd ..