version: "3.7"
services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    networks:
      - dev
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    networks:
      - frontend
      - dev
    ports:
      - "8088:8080"
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=guacamoleDB
      - MYSQL_DATABASE=guacamole
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=${GUACAMOLE_DB}
    restart: unless-stopped
#   traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:guac.${DOMAINNAME}"
      - "traefik.frontend.headers.frameDeny=false"

  guacamoleDB:
    image: mysql:latest
    container_name: guacamoleDB
    networks:
      - "dev"
    environment:
      - MYSQL_ROOT_PASSWORD=${GUACAMOLE_DB_ROOT}
      - MYSQL_DATABASE=guacamole
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=${GUACAMOLE_DB}
#    ports:
#      - "3306:3306"
    volumes:
      - ${CONFIGDIR}/dev/guacamoleDB/config:/etc/mysql/conf.d
      - ${CONFIGDIR}/dev/guacamoleDB/db:/var/lib/mysql
      - ${CONFIGDIR}/dev/guacamoleDB/scripts:/tmp/scripts
    restart: unless-stopped

# docker run -d -v jenkins_home:/var/jenkins_home -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - "dev"
      - "frontend"
    volumes:
      - ${CONFIGDIR}/dev/jenkins:/var/jenkins_home
    ports:
      - 8083:8080
      - 50000:50000
    restart: unless-stopped
#   traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:jenkins.${DOMAINNAME}"
      - "traefik.frontend.headers.frameDeny=false"

networks:
  frontend:
    external:
      name: "frontend"
  dev:
    name: "dev"
