version: "3.7"
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    networks:
      - int
      - ext
      - media
#    network_mode: host
    volumes:
      - ${CONFIGDIR}/media/plex/config:/config
      - ${STORAGEDIR}/media/tvshows:/data/tvshows
      - ${STORAGEDIR}/media/movies:/data/movies
      - ${CONFIGDIR}/media/plex/transcode:/transcode
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${INT}:32400:32400/tcp
      - ${INT}:3005:3005/tcp
      - ${INT}:8324:8324/tcp
      - ${INT}:32469:32469/tcp
      - ${INT}:1900:1900/udp
      - ${INT}:32410:32410/udp
      - ${INT}:32412:32412/udp
      - ${INT}:32413:32413/udp
      - ${INT}:32414:32414/udp
    restart: unless-stopped
#   traefik
    labels:
      - traefik.enable=true
      - traefik.port=32400
      - traefik.frontend.rule=Host:plex.${DOMAINNAME}
      - traefik.frontend.headers.frameDeny=false

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      - int
      - media
    volumes:
      - ${CONFIGDIR}/media/jellyfin/config:/config
      - ${CONFIGDIR}/media/jellyfin/cache:/cache
      - ${STORAGEDIR}/media:/media:ro
    ports:
      # - ${INT}:8096:8096
      # - ${INT}:8920:8920
      - ${INT}:7359:7359
      - ${INT}:1900:1900
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.port=8096
      - traefik.frontend.rule=Host:jellyfin.${DOMAINNAME}
      - traefik.frontend.headers.frameDeny=false

  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    networks:
      - int
      - media
    volumes:
      - ${CONFIGDIR}/media/tautulli:/config
      - ${CONFIGDIR}/media/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#    ports:
#      - ${INT}:8181:8181
    restart: unless-stopped
#   traefik
    labels:
      - traefik.enable=true
      - traefik.port=8181
      - traefik.frontend.rule=Host:tautulli.${DOMAINNAME}
      - traefik.frontend.headers.frameDeny=false

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - int
      - media
    volumes:
      - ${CONFIGDIR}/media/radarr:/config
      - ${STORAGEDIR}/media/movies:/movies
      - ${STORAGEDIR}/download:/downloads
#    ports:
#      - ${INT}:7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
#   traefik
    labels:
      - traefik.enable=true
      - traefik.port=7878
      - traefik.frontend.rule=Host:radarr.${DOMAINNAME}
      - traefik.frontend.headers.frameDeny=false

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - int
      - media
    volumes:
      - ${CONFIGDIR}/media/sonarr:/config
      - ${STORAGEDIR}/media/tvshows:/tv
      - ${STORAGEDIR}/download:/downloads
#    ports:
#      - ${INT}:8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
#   traefik
    labels:
      - traefik.enable=true
      - traefik.port=8989
      - traefik.frontend.rule=Host:sonarr.${DOMAINNAME}
      - traefik.frontend.headers.frameDeny=false

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    networks:
      - int
      - media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/media/jackett:/config
      - ${STORAGEDIR}/download:/downloads
#    ports:
#      - ${INT}:9117:9117
    restart: unless-stopped
    #traefik
    labels:
      - traefik.enable=true
      - traefik.port=9117
      - traefik.frontend.rule=Host:jackett.${DOMAINNAME}
      - traefik.frontend.headers.frameDeny=false

  organizr:
    image: lsiocommunity/organizr:latest
    container_name: organizr
    networks:
      - int
      - media
#    ports:
#      - ${INT}:80:80
    volumes:
      - ${CONFIGDIR}/media/organizr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
#   traefik
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:organizr.${DOMAINNAME}
      - traefik.frontend.headers.frameDeny=false

networks:
  int:
    external:
      name: int
  ext:
    external:
      name: ext
  media:
    name: media
