version: "3.7"
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: mc
    networks:
      - "frontend"
      - "minecraft"
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - VERSION=1.14.4
      - OPS=ryancluff
      - MEMORY=4G
    volumes:
      - ${CONFIGDIR}/minecraft/standard/data:/data
      - ${CONFIGDIR}/minecraft/standard/config:/config
      - ${CONFIGDIR}/minecraft/standard/mods:/mods
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:minecraft.${DOMAINNAME}"
      - "traefik.port=25565"
    restart: unless-stopped

  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: bedrock
    networks:
      - "frontend"
      - "minecraft"
    ports:
      - "19132:19132/udp"
    environment:
      - SERVER_NAME=TheCommune
      - DIFFICULTY=normal
      - EULA=TRUE
    volumes:
      - ${CONFIGDIR}/minecraft/bedrock/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:bedrock.${DOMAINNAME}"
      - "traefik.port=19132"
    restart: unless-stopped

networks:
  frontend:
    external:
      name: "frontend"
  minecraft:
    name: "minecraft"
