version: "3.7"
services:
  minecraft-java:
    image: itzg/minecraft-server
    container_name: mc
    networks:
      - minecraft
    ports:
      - ${INT}:25565:25565
      - ${EXT}:25565:25565
    environment:
      - EULA=TRUE
      - OPS=ryancluff
      - MEMORY=4G
    volumes:
      - ${CONFIGDIR}/minecraft/standard/data:/data
      - ${CONFIGDIR}/minecraft/standard/config:/config
      - ${CONFIGDIR}/minecraft/standard/mods:/mods
    restart: unless-stopped

  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: bedrock
    networks:
      - minecraft
    ports:
      - ${INT}:19132:19132/udp
      - ${EXT}:19132:19132/udp
    environment:
      - SERVER_NAME=TheCommune
      - DIFFICULTY=normal
      - EULA=TRUE
    volumes:
      - ${CONFIGDIR}/minecraft/bedrock/data:/data
    restart: unless-stopped

networks:
  int:
    external:
      name: int
  ext:
    external:
      name: ext
  minecraft:
    name: minecraft
