version: "3.7"
services:
  minecraft-java:
    image: itzg/minecraft-server
    container_name: mc
    networks:
      - frontend
      - minecraft
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - VERSION=1.14.4
      - OPS=ryancluff
      - MEMORY=4G
    volumes:
      - ${CONFIGDIR}/minecraft/standard/data:/data
      - ${CONFIGDIR}/minecraft/standard/config:/config
      - ${CONFIGDIR}/minecraft/standard/mods:/mods
    restart: unless-stopped

  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: bedrock
    networks:
      - frontend
      - minecraft
    ports:
      - 19132:19132
    environment:
      - SERVER_NAME=TheCommune
      - DIFFICULTY=normal
      - EULA=TRUE
    volumes:
      - ${CONFIGDIR}/minecraft/bedrock/data:/data
    restart: unless-stopped

networks:
  frontend:
    external:
      name: frontend
  minecraft:
    name: minecraft
